Repository VirtoCommerce/vc-module-catalog-export-import, pull requests merged in 2021-09, with the labels that each got.

#11 VDS-2570: Add preview for descriptions import
  src/VirtoCommerce.DescriptionExportImportModule.Core/Models/CsvEditorialReview.cs
  src/VirtoCommerce.DescriptionExportImportModule.Core/Models/ImportConfiguration.cs
  src/VirtoCommerce.DescriptionExportImportModule.Core/Models/ImportDataPreview.cs
  src/VirtoCommerce.DescriptionExportImportModule.Core/Models/ImportDataPreviewRequest.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Services/CsvDataValidator.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Services/CsvPagedDataImporter.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Services/CsvPagedEditorialReviewDataImporter.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Services/ExportPagedDataSource.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Validation/ImportReviewValidator.cs
  src/VirtoCommerce.DescriptionExportImportModule.Web/Content/css/descriptions-export-import.css
  src/VirtoCommerce.DescriptionExportImportModule.Web/Controllers/Api/ImportController.cs
  src/VirtoCommerce.DescriptionExportImportModule.Web/Localizations/en.VirtoCommerce.DescriptionExportImport.json
  src/VirtoCommerce.DescriptionExportImportModule.Web/Scripts/blades/file-upload.js
  src/VirtoCommerce.DescriptionExportImportModule.Web/Scripts/blades/file-upload.tpl.html
  src/VirtoCommerce.DescriptionExportImportModule.Web/Scripts/blades/import-preview.js
  src/VirtoCommerce.DescriptionExportImportModule.Web/Scripts/blades/import-preview.tpl.html
  src/VirtoCommerce.DescriptionExportImportModule.Web/Scripts/module.js
  src/VirtoCommerce.DescriptionExportImportModule.Web/Scripts/resources/import.js
  src/VirtoCommerce.DescriptionExportImportModule.Web/package-lock.json
  src/VirtoCommerce.DescriptionExportImportModule.Web/package.json
Labels: deploy-qa

#10 VDS-2579: Error report
  src/VirtoCommerce.DescriptionExportImportModule.Core/ModuleConstants.cs
  src/VirtoCommerce.DescriptionExportImportModule.Core/Services/ICsvImportReporter.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Services/CsvImportReporter.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Services/CsvPagedDataImporter.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Validation/ImportEntityIsNotDuplicateValidator.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Validation/ImportReviewValidator.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Validation/ImportReviewsValidator.cs
  src/VirtoCommerce.DescriptionExportImportModule.Web/Content/css/descriptions-export-import.css
  src/VirtoCommerce.DescriptionExportImportModule.Web/Module.cs
  src/VirtoCommerce.DescriptionExportImportModule.Web/Scripts/blades/import-preview.js
  src/VirtoCommerce.DescriptionExportImportModule.Web/package-lock.json
Labels: deploy-qa, deploy-demo

#12 VDS-2593 [Export] Export descriptions with selected filter
  src/VirtoCommerce.DescriptionExportImportModule.Core/Models/ExportDataRequest.cs
  src/VirtoCommerce.DescriptionExportImportModule.Core/Models/ExportTotalCountResponse.cs
  src/VirtoCommerce.DescriptionExportImportModule.Core/Models/ProductDescriptionSearchCriteria.cs
  src/VirtoCommerce.DescriptionExportImportModule.Core/Services/IListEntryIndexedSearchService.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Services/ExportPagedDataSource.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Services/ListEntryIndexedSearchService.cs
  src/VirtoCommerce.DescriptionExportImportModule.Data/Services/ProductEditorialReviewSearchService.cs
  src/VirtoCommerce.DescriptionExportImportModule.Web/Controllers/Api/ExportController.cs
  src/VirtoCommerce.DescriptionExportImportModule.Web/Localizations/en.VirtoCommerce.DescriptionExportImport.json
  src/VirtoCommerce.DescriptionExportImportModule.Web/Module.cs
  src/VirtoCommerce.DescriptionExportImportModule.Web/Scripts/blades/export-processing.js
  src/VirtoCommerce.DescriptionExportImportModule.Web/Scripts/dialogs/export-descriptions-confirm-dialog.tpl.html
  src/VirtoCommerce.DescriptionExportImportModule.Web/Scripts/resources/export.js
Labels: deploy-demo
